### ISSUE TITLE
Authentication error with zone DNS API token

### ISSUE THREAD

**Issue by mbrodala** [tiredofit/docker-traefik-cloudflare-companion#44]
For minimal permissions I have created an API token locked down to zone DNS edits using the "Edit zone DNS" template:

![image](https://user-images.githubusercontent.com/5037116/109297795-dad4a900-7832-11eb-9e81-78f9367c2dcd.png)

![image](https://user-images.githubusercontent.com/5037116/109297630-9812d100-7832-11eb-9ab9-d40b4f6fba77.png)

When launching this service I get an `Authentication error`:

```
app-cloudflare-companion | [INFO] ** [traefik-cloudflare-companion] Starting Traefik Cloudflare Companion
app-cloudflare-companion | Traceback (most recent call last):
app-cloudflare-companion |   File "/usr/sbin/cloudflare-companion", line 276, in <module>
app-cloudflare-companion |     init(doms)
app-cloudflare-companion |   File "/usr/sbin/cloudflare-companion", line 211, in init
app-cloudflare-companion |     check_container_t2(c, doms)
app-cloudflare-companion |   File "/usr/sbin/cloudflare-companion", line 176, in check_container_t2
app-cloudflare-companion |     point_domain(extracted_domains[0], doms)
app-cloudflare-companion |   File "/usr/sbin/cloudflare-companion", line 91, in point_domain
app-cloudflare-companion |     records = cf.zones.dns_records.get(dom['zone_id'], params={u'name': name})
app-cloudflare-companion |   File "/usr/lib/python3.8/site-packages/CloudFlare/cloudflare.py", line 672, in get
app-cloudflare-companion |     return self._base.call_with_auth('GET', self._parts,
app-cloudflare-companion |   File "/usr/lib/python3.8/site-packages/CloudFlare/cloudflare.py", line 126, in call_with_auth
app-cloudflare-companion |     return self._call(method, headers, parts,
app-cloudflare-companion |   File "/usr/lib/python3.8/site-packages/CloudFlare/cloudflare.py", line 502, in _call
app-cloudflare-companion |     raise CloudFlareAPIError(code, message)
app-cloudflare-companion | CloudFlare.exceptions.CloudFlareAPIError: Authentication error
```

Am I missing other permissions?

**Comment by mbrodala** [comment]
By now I've switched to a wildcard certificate, thus I don't need specific DNS entries (and this image) anymore.

Still it would be interesting what the issue could be here.

**Comment by SebDanielsson** [comment]
Yeah I'm getting the same error myself even after generating a token with full permissions. Either the documentation is bad or something is broken for now..

**Comment by Northguy** [comment]
Same issue here upon launching the service... no clue on how to debug unfortunately :-(

**Comment by Northguy** [comment]
OK, figured it out. Please note the comment **Leave Blank for Scoped API** behind the CF_EMAIL environment variable. This is important! You need to remove the CF_EMAIL environment variable when using a domain specific API token!

The long explanation:

According to Cloudflare documentation [here](https://support.cloudflare.com/hc/en-us/articles/200167836-Managing-API-Tokens-and-Keys#h_1f3ebJto7XkuFLpSvvBP68) one of the common issues with API tokens is using the wrong authentication. 

> On occasion, customers will attempt to use an API Token with an API Key syntax. Ensure you are using the Bearer option, rather than the Email and API key pair.

According to the documentation of the [Python wrapper for the Cloudflare v4 API](https://pypi.org/project/cloudflare/), there are  multiple ways to make a call:

   `# A minimal call - reading values from environment variables or configuration file
    cf = CloudFlare.CloudFlare()

    # A minimal call with debug enabled
    cf = CloudFlare.CloudFlare(debug=True)

    # An authenticated call using an API Token (note the missing email)
    cf = CloudFlare.CloudFlare(token='00000000000000000000000000000000')

    # An authenticated call using an API Key
    cf = CloudFlare.CloudFlare(email='user@example.com', token='00000000000000000000000000000000')

    # An authenticated call using an API Key and CA-Origin info
    cf = CloudFlare.CloudFlare(email='user@example.com', token='00000000000000000000000000000000', certtoken='v1.0-...')

    # An authenticated call using using a stored profile (see below)
    cf = CloudFlare.CloudFlare(profile="CompanyX"))`

As we are using an API token, we need to use the 1st option of the authenticated call and **omit** the e-mail address.

**Comment by SebDanielsson** [comment]
Good catch, now it's working. Thanks!
