### ISSUE TITLE
No Connection Adapters were found

### ISSUE THREAD

**Issue by ntatschner** [tiredofit/docker-traefik-cloudflare-companion#82]
### Summary

Traceback (most recent call last):
  File "/usr/sbin/cloudflare-companion", line 512, in <module>
    sync_mappings(get_initial_mappings(traefik_included_hosts, traefik_excluded_hosts), doms)
  File "/usr/sbin/cloudflare-companion", line 403, in get_initial_mappings
    add_to_mappings(mappings, check_traefik(included_hosts, excluded_hosts))
  File "/usr/sbin/cloudflare-companion", line 328, in check_traefik
    r = requests.get("{}/api/http/routers".format(TRAEFIK_POLL_URL))
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 695, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'tcp://REDACTED:443/api/http/routers'

- Image version / tag:  latest

**Comment by AlexanderEDavis** [comment]
I'm also having this issue, did you find what was wrong?
