### ISSUE TITLE
Could not route to /client/v4/zones/dns_records

### ISSUE THREAD

**Issue by ChristianOrrala** [tiredofit/docker-traefik-cloudflare-companion#88]
### Summary

Hi, I tried to set up the companion, buy I'm getting this error in the logs... 

`CloudFlare.exceptions.CloudFlareAPIError: Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?`

Is this a known error? thank you for the support.

### Steps to reproduce

Fresh install of the companion on a working traefik instance.

### What is the expected *correct* behavior?

The companion should be able to query the cloudflare API

### Relevant logs and/or screenshots

```
2023-04-19.00:23:01 [STARTING] ** [traefik-cloudflare-companion] [9] Starting Traefik Cloudflare Companion
2023-04-19T00:23:02-0600 INFO | Found Service ID: b76fc09d63fda3332b34707ca9acdee1622185c5c32d2aea6afe8244 with Hostname traefik.domain.com
2023-04-19T00:23:02-0600 INFO | Found Traefik Router Name: api@docker with Hostname raefik.domain.com
2023-04-19T00:23:02-0600 INFO | Found Traefik Router Name: nextcloud@docker with Hostname raefik.domain.com
2023-04-19T00:23:02-0600 INFO | Found Traefik Router Name: tautulli@docker with Hostname raefik.domain.com
Traceback (most recent call last):
  File "/usr/sbin/cloudflare-companion", line 549, in <module>
    sync_mappings(get_initial_mappings(traefik_included_hosts, traefik_excluded_hosts), doms)
  File "/usr/sbin/cloudflare-companion", line 403, in sync_mappings
    if point_domain(k, domain_infos):
  File "/usr/sbin/cloudflare-companion", line 175, in point_domain
    records = cf.zones.dns_records.get(domain_info['zone_id'], params={u'name': name})
  File "/usr/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 674, in get
    return self._base.do_auth('GET', self._parts, [identifier1, identifier2, identifier3, identifier4], params, data)
  File "/usr/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 129, in do_auth
    return self._call(method, headers, parts, identifiers, params, data, files)
  File "/usr/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 502, in _call
    raise CloudFlareAPIError(code, message)
CloudFlare.exceptions.CloudFlareAPIError: Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?
```

### Environment

- Image version / tag:  tiredofit/traefik-cloudflare-companion:latest
- Host OS: UNRAID  6.12.0-rc3

    
### Possible fixes
It could be an issue with the Cloudflare API.

**Comment by ChristianOrrala** [comment]
The issue was an empty domain was being parsed, I removed the variable, and it works.
